In [1]:
import numpy as np
import torch

In [2]:
data = [[1,2],[3,4]]

In [3]:
tensor_data = torch.tensor(data)

In [4]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array = np.array(data)
# 从numpy转换为torch的tensor，但是共享同一块内存
tensor_np = torch.from_numpy(np_array)
print(f"Tensor from list: {tensor_data}")
print(f"Tensor from np_array: {tensor_np}")

Tensor from list: tensor([[1, 2],
        [3, 4]])
Tensor from np_array: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [11]:
# 以numpy数组直接初始化tensor对象，得到的tensor是
tensor_np2 = torch.tensor(np_array)
print(f"Tensor from nparray of torch.tensor: {tensor_np2}")

Tensor from nparray of torch.tensor: tensor([[ 8, 16],
        [ 9, 18]], dtype=torch.int32)


In [10]:
np.multiply(np_array, 2, out=np_array)
print(f"After mul nparray:{np_array}")
print(f"After Mul tensor:{tensor_np}")

After mul nparray:[[2 4]
 [6 8]]
After Mul tensor:tensor([[2, 4],
        [6, 8]], dtype=torch.int32)


In [11]:
print(f"After mul Tensor np2:{tensor_np2}")

After mul Tensor np2:tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


## 使用torch.from_numpy的会共享内存，直接使用torch.tensor的不会共享内存

In [13]:
np_array = np_array * 3

In [14]:
print(f"After * nparray:{np_array}")

After * nparray:[[ 6 12]
 [18 24]]


In [15]:
print(f"After * tensor_np:{tensor_np}")

After * tensor_np:tensor([[2, 4],
        [6, 8]], dtype=torch.int32)


## 使用四则运算符操作np.array，结果不会同步到tensor

In [16]:
tensor_np = torch.from_numpy(np_array)
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[ 6 12]
 [18 24]]
tensor np:tensor([[ 6, 12],
        [18, 24]], dtype=torch.int32)


In [19]:
torch.mul(tensor_np, 2, out=tensor_np)
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[12 24]
 [36 48]]
tensor np:tensor([[12, 24],
        [36, 48]], dtype=torch.int32)


In [20]:
np_array -= 4
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[ 8 20]
 [32 44]]
tensor np:tensor([[ 8, 20],
        [32, 44]], dtype=torch.int32)


In [22]:
np_array *= 2
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[ 32  80]
 [128 176]]
tensor np:tensor([[ 32,  80],
        [128, 176]], dtype=torch.int32)


In [23]:
np_array = np_array- 30
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[  2  50]
 [ 98 146]]
tensor np:tensor([[ 32,  80],
        [128, 176]], dtype=torch.int32)


## op=运算符，不会改变原引用的地址，所以仍然可以实现np和tensor的共享，而 x = x op a则不行,同时，矩阵乘法不支持op=

In [33]:
np_array = np.array([[2,3],[1,4]])

In [34]:
tensor_np = torch.from_numpy(np_array)

In [23]:
np_other = np.array([[1,2],[2,4]])


In [24]:
np.dot(np_array, np_other, out=np_array)
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[ 8 16]
 [ 9 18]]
tensor np:tensor([[ 8, 16],
        [ 9, 18]], dtype=torch.int32)


In [25]:
tensor_other = torch.from_numpy(np_other)

In [31]:
tensor_np = torch.from_numpy(np_array)
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

Now nparray:[[2 3]
 [1 4]]
tensor np:tensor([[2, 3],
        [1, 4]], dtype=torch.int32)


In [16]:
tensor_np = torch.tensor([[2,3],[1,4]], dtype=torch.int32)
tensor_np2 = torch.tensor([[8,10],[9,3]], dtype=torch.int32)
print(tensor_np, tensor_np2)

tensor([[2, 3],
        [1, 4]], dtype=torch.int32) tensor([[ 8, 10],
        [ 9,  3]], dtype=torch.int32)


In [21]:
new_tensor = torch.ones((2,2), dtype=torch.int32)
# torch.mm(tensor_np, tensor_np2, out=tensor_np)
tensor_np = torch.mm(tensor_np, tensor_np2, out=new_tensor)
print(new_tensor)

tensor([[605, 517],
        [550, 506]], dtype=torch.int32)


## 如上，torch进行矩阵运算时，不可使用参与计算的变量作为out，会导致变量值错误


In [22]:
print(f"Now nparray:{np_array}\ntensor np:{tensor_np}")

NameError: name 'np_array' is not defined

## 使np.dot能够实现内存共享

In [1]:
tensor_ones = torch.ones_like(tensor_np)
tensor_rands = torch.rand_like(tensor_np, dtype=torch.float)

NameError: name 'torch' is not defined

In [44]:
print(f"ones_like:{tensor_ones}, rand_like:{tensor_rands}")

ones_like:tensor([[1, 1],
        [1, 1]], dtype=torch.int32), rand_like:tensor([[0.9145, 0.4618],
        [0.7713, 0.8979]])


In [45]:
tensor_copy = torch.tensor(tensor_np)

C:\Users\hongx\AppData\Local\Temp\ipykernel_31112\111225008.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_copy = torch.tensor(tensor_np)


In [59]:
torch.add(tensor_np, 2, out=tensor_np)

tensor([[16, 16],
        [16, 16]], device='cuda:0', dtype=torch.int32)

In [49]:
tensor_copy = tensor_np.clone().detach()

In [52]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"{rand_tensor}\n{ones_tensor}\n{zeros_tensor}")

tensor([[0.1442, 0.7364, 0.9531],
        [0.1996, 0.7469, 0.1518]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [53]:
print(f"Shape:{rand_tensor.shape}\ndtype:{rand_tensor.dtype}\ndevice:{rand_tensor.device}")

Shape:torch.Size([2, 3])
dtype:torch.float32
device:cpu


In [23]:
torch.cuda.is_available()

True

In [24]:
# 使用tensor.to("cuda")来实现转换为cuda变量
tensor_np =tensor_np.to("cuda")

In [25]:
tensor_np

tensor([[605, 517],
        [550, 506]], device='cuda:0', dtype=torch.int32)

In [28]:
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name(i))

NVIDIA GeForce RTX 4070 Laptop GPU


## Tensor To cuda之后会失去和numpy的联系

In [60]:
tensor_new = torch.randint(1, 100, (3,5))

In [66]:
print(f"Full: {tensor_new}\nFirst Row:{tensor_new[0,:]}\nFirst Column:{tensor_new[:,0]}\nLast Column:{tensor_new[:,-1]}")

Full: tensor([[19, 80, 28, 74, 22],
        [99, 52, 11, 54, 42],
        [56, 43, 82, 99, 81]])
First Row:tensor([19, 80, 28, 74, 22])
First Column:tensor([19])
Last Column:tensor([22, 42, 81])


In [67]:
tensor_new[:,::2] = 0
print(f"隔两列归零：{tensor_new}")

隔两列归零：tensor([[ 0, 80,  0, 74,  0],
        [ 0, 52,  0, 54,  0],
        [ 0, 43,  0, 99,  0]])


In [68]:
tensor_new = torch.randint(10, 20, (5,3))
tensor_new_2 = torch.randint(30,60, (5,4))
tensor_new_3 = torch.randint(70,100, (5,3))

In [73]:
t_all = torch.cat([tensor_new, tensor_new_2, tensor_new_3], dim=1)

In [74]:
t_all

tensor([[15, 14, 14, 57, 40, 48, 47, 82, 77, 99],
        [16, 12, 19, 32, 40, 48, 46, 95, 91, 97],
        [12, 16, 12, 49, 56, 46, 59, 74, 86, 97],
        [14, 12, 12, 51, 40, 51, 50, 78, 71, 99],
        [14, 19, 14, 31, 32, 55, 55, 79, 85, 80]])

In [75]:
tensor_row_new = torch.randint(1,5, (5,3))
tensor_row_new_2 = torch.randint(10,20, (4,3))
tensor_row_new_3 = torch.randint(40,60,(3,3))
t_row_all = torch.cat([tensor_row_new, tensor_row_new_2, tensor_row_new_3], dim=0)
print(t_row_all)

tensor([[ 4,  2,  3],
        [ 1,  3,  4],
        [ 3,  1,  3],
        [ 3,  4,  4],
        [ 3,  4,  4],
        [13, 14, 17],
        [14, 15, 11],
        [11, 18, 17],
        [10, 17, 11],
        [50, 48, 59],
        [43, 41, 43],
        [48, 46, 53]])


## torch的cat函数，dim为几，第几维度的大小就会发生变化，即在第几维上拼接

In [76]:
tensor_for_calc = torch.randint(10,20, (5,3))

In [80]:
y1 = tensor_for_calc @ tensor_for_calc.T
y2 = tensor_for_calc.matmul(tensor_for_calc.T)
y3 = tensor_for_calc.mm(tensor_for_calc.T)
y4 = tensor_for_calc.matmul(tensor_for_calc.transpose(0, 1))
print(f"origin: {tensor_for_calc}\n.T: {tensor_for_calc.T}\n.transpose: {tensor_for_calc.transpose(0,1)}\n{y1}\n{y2}\n{y3}\n{y4}")

origin: tensor([[17, 13, 11],
        [18, 13, 11],
        [12, 14, 19],
        [13, 19, 15],
        [19, 17, 14]])
.T: tensor([[17, 18, 12, 13, 19],
        [13, 13, 14, 19, 17],
        [11, 11, 19, 15, 14]])
.transpose: tensor([[17, 18, 12, 13, 19],
        [13, 13, 14, 19, 17],
        [11, 11, 19, 15, 14]])
tensor([[579, 596, 595, 633, 698],
        [596, 614, 607, 646, 717],
        [595, 607, 701, 707, 732],
        [633, 646, 707, 755, 780],
        [698, 717, 732, 780, 846]])
tensor([[579, 596, 595, 633, 698],
        [596, 614, 607, 646, 717],
        [595, 607, 701, 707, 732],
        [633, 646, 707, 755, 780],
        [698, 717, 732, 780, 846]])
tensor([[579, 596, 595, 633, 698],
        [596, 614, 607, 646, 717],
        [595, 607, 701, 707, 732],
        [633, 646, 707, 755, 780],
        [698, 717, 732, 780, 846]])
tensor([[579, 596, 595, 633, 698],
        [596, 614, 607, 646, 717],
        [595, 607, 701, 707, 732],
        [633, 646, 707, 755, 780],
        [698, 7

In [83]:
tensor_calc_2 = torch.randint(1,4, (3,4))
z1 = tensor_calc_2 * tensor_calc_2
z2 = tensor_calc_2.mul(tensor_calc_2)
z3 = torch.ones_like(tensor_calc_2)

torch.mul(tensor_calc_2, tensor_calc_2, out=z3)

print(f"ori:{tensor_calc_2}\n{z1}\n{z2}\n{z3}")

ori:tensor([[1, 1, 1, 2],
        [3, 3, 3, 2],
        [1, 2, 1, 3]])
tensor([[1, 1, 1, 4],
        [9, 9, 9, 4],
        [1, 4, 1, 9]])
tensor([[1, 1, 1, 4],
        [9, 9, 9, 4],
        [1, 4, 1, 9]])
tensor([[1, 1, 1, 4],
        [9, 9, 9, 4],
        [1, 4, 1, 9]])


In [84]:
total = tensor_calc_2.sum()
total_item = total.item()
print(f"{total.type()}\n{type(total)}\n{type(total_item)}")

torch.LongTensor
<class 'torch.Tensor'>
<class 'int'>


In [85]:
print(tensor_calc_2)
tensor_calc_2.t_()
print(tensor_calc_2)
tensor_calc_2.add_(30)
print(tensor_calc_2)

tensor([[1, 1, 1, 2],
        [3, 3, 3, 2],
        [1, 2, 1, 3]])
tensor([[1, 3, 1],
        [1, 3, 2],
        [1, 3, 1],
        [2, 2, 3]])
tensor([[31, 33, 31],
        [31, 33, 32],
        [31, 33, 31],
        [32, 32, 33]])


## 操作函数后面加下划线的效果相当于op=

In [86]:
np_bridge = tensor_calc_2.numpy()
print(np_bridge)
tensor_calc_2.add_(3)
print(np_bridge)
print(f"type of np_bridge:{type(np_bridge)}")


[[31 33 31]
 [31 33 32]
 [31 33 31]
 [32 32 33]]
[[34 36 34]
 [34 36 35]
 [34 36 34]
 [35 35 36]]
type of np_bridge:<class 'numpy.ndarray'>


In [87]:
np_bridge += 6

In [88]:
print(tensor_calc_2)

tensor([[40, 42, 40],
        [40, 42, 41],
        [40, 42, 40],
        [41, 41, 42]])


In [89]:
tensor_cuda = tensor_calc_2.to("cuda")
np_cuda_bridge = tensor_cuda.numpy()

print(f"tensor_cuda:{tensor_cuda}, np_cuda_bridge:{np_cuda_bridge}")

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [91]:
np_cuda_bridge = tensor_cuda.cpu().numpy()
np_cuda_bridge += 3

print(f"tensor_cuda:{tensor_cuda}, np_cuda_bridge:{np_cuda_bridge}")

tensor_cuda:tensor([[40, 42, 40],
        [40, 42, 41],
        [40, 42, 40],
        [41, 41, 42]], device='cuda:0'), np_cuda_bridge:[[43 45 43]
 [43 45 44]
 [43 45 43]
 [44 44 45]]


## np bridge和tensor共享内存,但cuda中存储的tensor无法直接转换成np,使用.cpu()转换之后就失去了内存共享特性

In [30]:
torch.cuda.get_device_name()


'NVIDIA GeForce RTX 4070 Laptop GPU'

In [95]:
import platform
platform.processor()

'Intel64 Family 6 Model 183 Stepping 1, GenuineIntel'